on:
  push:
    branches:
      - main

  
jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2



      - name: export game
        id: export
        # Use latest version (see releases for all versions)
        uses: firebelley/godot-export@v5.2.1
        with:
            # Defining all the required inputs
            godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_linux.x86_64.zip
            godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_export_templates.tpz
            relative_project_path: ./
            relative_export_path: ./builds/web
            archive_output: false

            
      - name: Upload to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          ITCH_GAME: untitled-wild-game
          ITCH_USER: phorpho
          PACKAGE: ./builds/web